services:
  frontend:
    profiles: ["frontend"]
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - db
  backend:
    profiles: ["backend"]
    build: ./server
    ports:
      - "8080:9000"
  keycloak:
    profiles: ["frontend", "backend"]
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
