services:
  frontend:
    profiles: ["frontend"]
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - keycloak
      - backend
  backend:
    profiles: ["backend"]
    build: ./server
    ports:
      - "8080:8080"
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8088:8080"
