services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8088:8080"
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - keycloak
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
