services:
  web:
    profiles: ["frontend"]
    build: .
    ports:
      - "8000:80"
    depends_on:
      - keycloak
      - db
  db:
    profiles: ["dev"]
    build: db 
    ports:
      - "3000:3000"
    volumes:
      - ./db:/data
    command: -H 0.0.0.0 -w /data/data.json
  keycloak:
    profiles: ["dev"]
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
